[package]
name = "circle-plonk-dsl-fields"
version = "0.1.0"
edition = "2021"

[dependencies]
stwo.workspace = true
stwo-examples.workspace = true
circle-plonk-dsl-constraint-system = { path = "../../constraint_system" }
num-traits.workspace = true
rand.workspace = true
